//! Generate a stub-handler source file from a configured service builder.
//!
//! Intended as a development-time aid: emit a compilable Rust file containing
//! one async handler per (entity-set × verb) and per (entity-set × contained-
//! navigation-property × verb) the service builder expects, plus a `register`
//! function that wires them all up. Each handler returns
//! `StatusCode::NOT_IMPLEMENTED`; the developer fills them in.
//!
//! Typical use, from a service's `main()`:
//!
//! ```ignore
//! let builder = ODataServiceBuilder::from_csdl(csdl)?;
//! #[cfg(debug_assertions)]
//! std::fs::write("target/scaffold.rs", builder.scaffold()).unwrap();
//! let app = builder.with_state(pool).entity_set(...).build();
//! ```
//!
//! The output references `odata_service` and `axum` types by name. The
//! codegen lives here, where the handler signatures live — `csdl-edm` has
//! no knowledge of the service layer.

use std::fmt::Write;

use crate::schema_view::Schema;

/// Render the scaffold source for `schema`. Crate-private; the public entry
/// point is [`crate::ODataServiceBuilder::scaffold`].
pub(crate) fn render(schema: &Schema) -> String {
    let mut out = String::new();
    emit_header(&mut out, schema);
    for es in schema.entity_sets() {
        emit_entity_set_handlers(&mut out, schema, es);
    }
    emit_register(&mut out, schema);
    out
}

// ---------------------------------------------------------------------------
// Emitters
// ---------------------------------------------------------------------------

fn emit_header(out: &mut String, schema: &Schema) {
    writeln!(
        out,
        "// Generated by `odata_service::scaffold::Scaffold` from CSDL namespace `{}`.",
        schema.namespace
    )
    .unwrap();
    writeln!(out, "// Stub handlers + registration for the schema. Fill in the bodies;").unwrap();
    writeln!(out, "// the generator is meant as a starting point, not a finished file.").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "use axum::http::StatusCode;").unwrap();
    writeln!(out, "use axum::response::IntoResponse;").unwrap();
    writeln!(out, "use odata_service::{{").unwrap();
    writeln!(
        out,
        "    CollectionContext, ContainedCollectionContext, ContainedEntityContext, EntityContext,"
    )
    .unwrap();
    writeln!(out, "    ODataServiceBuilder,").unwrap();
    writeln!(out, "}};").unwrap();
    writeln!(out).unwrap();
}

fn emit_entity_set_handlers(out: &mut String, schema: &Schema, es: &crate::schema_view::EntitySet) {
    let set = &es.name;
    let type_name = &es.entity_type_name;
    let entity = singularize(set);

    writeln!(out, "// ----- {set} ({type_name}) -----").unwrap();
    writeln!(out).unwrap();

    emit_handler(out, &format!("list_{}", snake(set)), "CollectionContext");
    emit_handler(out, &format!("get_{}", snake(&entity)), "EntityContext");
    emit_handler(
        out,
        &format!("create_{}", snake(&entity)),
        "CollectionContext",
    );
    emit_handler(out, &format!("update_{}", snake(&entity)), "EntityContext");
    emit_handler(out, &format!("delete_{}", snake(&entity)), "EntityContext");

    if let Some(et) = schema.entity_type(type_name) {
        for nav in et.contained_nav_props() {
            emit_contained_handlers(out, set, &nav.name, &nav.target_type);
        }
    }
}

fn emit_contained_handlers(out: &mut String, set: &str, nav: &str, target_type: &str) {
    let child = singularize(nav);
    writeln!(out, "// {set} / {nav} (contained, {target_type})").unwrap();
    writeln!(out).unwrap();

    emit_handler(
        out,
        &format!("list_{}_{}", snake(set), snake(nav)),
        "ContainedCollectionContext",
    );
    emit_handler(
        out,
        &format!("get_{}_{}", snake(set), snake(&child)),
        "ContainedEntityContext",
    );
    emit_handler(
        out,
        &format!("create_{}_{}", snake(set), snake(&child)),
        "ContainedCollectionContext",
    );
    emit_handler(
        out,
        &format!("update_{}_{}", snake(set), snake(&child)),
        "ContainedEntityContext",
    );
    emit_handler(
        out,
        &format!("delete_{}_{}", snake(set), snake(&child)),
        "ContainedEntityContext",
    );
}

fn emit_handler(out: &mut String, name: &str, ctx_ty: &str) {
    writeln!(
        out,
        "async fn {name}(_ctx: {ctx_ty}, _state: ()) -> impl IntoResponse {{"
    )
    .unwrap();
    writeln!(out, "    StatusCode::NOT_IMPLEMENTED").unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn emit_register(out: &mut String, schema: &Schema) {
    writeln!(out, "/// Register every handler this schema declares.").unwrap();
    writeln!(
        out,
        "pub fn register(builder: ODataServiceBuilder<()>) -> ODataServiceBuilder<()> {{"
    )
    .unwrap();
    writeln!(out, "    builder").unwrap();

    for es in schema.entity_sets() {
        let set = &es.name;
        let entity = singularize(set);
        writeln!(out, "        .entity_set(\"{set}\", |es| {{").unwrap();
        writeln!(out, "            es.list(list_{})", snake(set)).unwrap();
        writeln!(out, "                .get(get_{})", snake(&entity)).unwrap();
        writeln!(out, "                .create(create_{})", snake(&entity)).unwrap();
        writeln!(out, "                .update(update_{})", snake(&entity)).unwrap();
        writeln!(out, "                .delete(delete_{})", snake(&entity)).unwrap();

        if let Some(et) = schema.entity_type(&es.entity_type_name) {
            for nav in et.contained_nav_props() {
                let n = &nav.name;
                let child = singularize(n);
                writeln!(out, "                .contained(\"{n}\", |nav| {{").unwrap();
                writeln!(
                    out,
                    "                    nav.list(list_{}_{})",
                    snake(set),
                    snake(n)
                )
                .unwrap();
                writeln!(
                    out,
                    "                        .get(get_{}_{})",
                    snake(set),
                    snake(&child)
                )
                .unwrap();
                writeln!(
                    out,
                    "                        .create(create_{}_{})",
                    snake(set),
                    snake(&child)
                )
                .unwrap();
                writeln!(
                    out,
                    "                        .update(update_{}_{})",
                    snake(set),
                    snake(&child)
                )
                .unwrap();
                writeln!(
                    out,
                    "                        .delete(delete_{}_{})",
                    snake(set),
                    snake(&child)
                )
                .unwrap();
                writeln!(out, "                }})").unwrap();
            }
        }

        writeln!(out, "        }})").unwrap();
    }
    writeln!(out, "}}").unwrap();
}

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

/// PascalCase / camelCase → snake_case. Non-alphanumerics become `_`.
fn snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    let mut prev_lower = false;
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            if ch.is_ascii_uppercase() {
                if prev_lower {
                    out.push('_');
                }
                out.push(ch.to_ascii_lowercase());
                prev_lower = false;
            } else {
                out.push(ch);
                prev_lower = ch.is_ascii_lowercase() || ch.is_ascii_digit();
            }
        } else {
            if !out.ends_with('_') && !out.is_empty() {
                out.push('_');
            }
            prev_lower = false;
        }
    }
    out
}

/// Heuristic singularizer. Handles the common English plural endings the
/// scaffold is likely to hit; for anything irregular the developer renames.
fn singularize(s: &str) -> String {
    if let Some(stem) = s.strip_suffix("ies") {
        return format!("{stem}y");
    }
    // -es plural endings where the stem keeps its trailing s/x/z/ch/sh:
    //   Buses → Bus, Boxes → Box, Matches → Match, Wishes → Wish.
    if let Some(stem) = s.strip_suffix("es") {
        let ends = |suf: &str| stem.ends_with(suf);
        if ends("s") || ends("x") || ends("z") || ends("ch") || ends("sh") {
            return stem.to_string();
        }
    }
    if let Some(stem) = s.strip_suffix('s')
        && !stem.is_empty()
        && !stem.ends_with('s')
    {
        return stem.to_string();
    }
    s.to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    const CSDL: &str = r#"
        <edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
          <edmx:DataServices>
            <Schema Namespace="BuildingManagement" xmlns="http://docs.oasis-open.org/odata/ns/edm">
                <EntityType Name="Printer" />
                <EntityType Name="Room">
                    <NavigationProperty Name="Printers" Type="Collection(BuildingManagement.Printer)" ContainsTarget="true" />
                </EntityType>
                <EntityContainer Name="Container">
                    <EntitySet Name="Rooms" EntityType="BuildingManagement.Room" />
                </EntityContainer>
            </Schema>
          </edmx:DataServices>
        </edmx:Edmx>
        "#;

    #[test]
    fn snake_case_basics() {
        assert_eq!(snake("Rooms"), "rooms");
        assert_eq!(snake("PrintQueueItems"), "print_queue_items");
        assert_eq!(snake("HTTPRequest"), "httprequest"); // good enough; uniform-upper runs collapse
        assert_eq!(snake("v2Items"), "v2_items");
    }

    #[test]
    fn singularize_common_plurals() {
        assert_eq!(singularize("Rooms"), "Room");
        assert_eq!(singularize("Printers"), "Printer");
        assert_eq!(singularize("Categories"), "Category");
        assert_eq!(singularize("Buses"), "Bus");
        // Irregular singulars (e.g. "Status", "News") are not handled — the
        // heuristic does best-effort and the developer renames if needed.
    }

    #[test]
    fn scaffold_contains_expected_handlers_and_registration() {
        let builder = crate::ODataServiceBuilder::from_csdl(CSDL).expect("csdl should parse");
        let src = builder.scaffold();

        // Entity-set verbs
        for needle in [
            "async fn list_rooms(_ctx: CollectionContext",
            "async fn get_room(_ctx: EntityContext",
            "async fn create_room(_ctx: CollectionContext",
            "async fn update_room(_ctx: EntityContext",
            "async fn delete_room(_ctx: EntityContext",
        ] {
            assert!(src.contains(needle), "missing fragment:\n{needle}\n---\n{src}");
        }

        // Contained-nav verbs
        for needle in [
            "async fn list_rooms_printers(_ctx: ContainedCollectionContext",
            "async fn get_rooms_printer(_ctx: ContainedEntityContext",
            "async fn delete_rooms_printer(_ctx: ContainedEntityContext",
        ] {
            assert!(src.contains(needle), "missing fragment:\n{needle}\n---\n{src}");
        }

        // Registration
        assert!(src.contains(".entity_set(\"Rooms\", |es| {"));
        assert!(src.contains(".contained(\"Printers\", |nav| {"));
        assert!(src.contains("pub fn register(builder: ODataServiceBuilder<()>)"));
    }
}
