
@baseUrl = http://localhost:3000

###
GET {{baseUrl}}/rooms

###
GET {{baseUrl}}/rooms?$top=2&$skip=1

###
GET {{baseUrl}}/rooms/oak-204


###
GET {{baseUrl}}/rooms/oak-204/printers


###
GET {{baseUrl}}/rooms/redw-1002/printers/prn1002-100



###
GET {{baseUrl}}/rooms/nowhere



###
POST {{baseUrl}}/rooms
Content-Type: application/json

{
  "id": "stda-204",
  "name": "Studio A 204"
}


###
GET {{baseUrl}}/rooms/stda-204
